
package miniexplorer;


import java.util.Date;
import javax.swing.Timer;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import com.sun.speech.freetts.VoiceManager;
import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.audio.JavaClipAudioPlayer;
//import com.sun.speech.freetts.en.us.CMUDiphoneVoice;
//import com.sun.speech.freetts.en.us.CMULexicon;
import java.text.DateFormat;
import javax.swing.JFrame;
import javax.swing.UIManager;

//import javax.swing.JWindow;
public class TalkingClock extends JFrame
{

    /** Creates new form MainForm */
    public TalkingClock()
    {
         try
        {
           // UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        }
        catch(Exception e){}
        initComponents();
        Timer tt = new Timer(1000, taskPerformer);
        tt.start();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        jButton1.setText(new Date().toString());
    }
    ActionListener taskPerformer = new ActionListener()
    {

        public void actionPerformed(ActionEvent evt)
        {
            jButton1.setText(new Date().toString());
        }
    };

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Digital Clock");
        setForeground(java.awt.Color.white);
        setLocationByPlatform(true);
        setMinimumSize(new java.awt.Dimension(500, 56));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 0, 32));
        jButton1.setAlignmentX(0.5F);
        jButton1.setBorder(null);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowClosed
    {//GEN-HEADEREND:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jButton1MouseClicked
    {//GEN-HEADEREND:event_jButton1MouseClicked
        // TODO add your handling code here:
        String sText;
        Date nulls=new Date();
        sText="The Time is : "+(DateFormat.getTimeInstance(DateFormat.SHORT).format(nulls));
        //sText = "Hello How are u?";
        if (sText != null && sText.trim().length() > 0)
        {
            VoiceManager voiceManager = null;
            Voice syntheticVoice = null;
            try
            {
                
//                Voice voice = new CMUDiphoneVoice();
// voice.setLexicon(new CMULexicon());
//
// // sets the AudioPlayer
// voice.setAudioPlayer(new JavaClipAudioPlayer());
//
// // loads the Voice
// voice.allocate();
//
// // start talking
// voice.speak("I can talk forever without getting tired!");
                voiceManager = VoiceManager.getInstance();
                syntheticVoice = voiceManager.getVoice("kevin");
                syntheticVoice.allocate();
                syntheticVoice.speak(sText);
                 // sets the Lexicon
                 
            }
            catch (Exception e)
            {
                e.printStackTrace();
            }
            finally
            {
                syntheticVoice.deallocate();
            }

        }
    }//GEN-LAST:event_jButton1MouseClicked
        private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
        {//GEN-HEADEREND:event_jButton1ActionPerformed
            // TODO add your handling code here:
        }//GEN-LAST:event_jButton1ActionPerformed

        /**
         * @param args the command line arguments
         */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {

            public void run()
            {
                new TalkingClock().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
